prodBuild/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("<int:id>", views.index, name="index"),
    # path("property/<int:id>", views.property, name="index"),
    path("", views.home, name="home"),
    path("create/", views.create, name="create"),
    path("view/", views.view, name="view"),
    path("propertyview/<int:id>", views.propertyview, name="view"),
    path('files/', views.file_list, name="file_list"),
    path('upload/', views.upload, name="upload"),
    path('files/upload/', views.file_upload, name="file_upload"),
    path('files/<int:pk>/', views.file_delete, name="file_delete"),
    # path('<str:url>', views.file_encrypt, name="file_encrypt"),
]

prodBuild/main/models.py
from django.db import models
from django.contrib.auth.models import User
from PyPDF2 import PdfFileReader, PdfFileWriter
import io

# Create your models here.


# Portfolio model
class Portfolio(models.Model):
    # Associates a user with each portfolio
    user = models.ForeignKey(
        # Sets deletion behavior, prevents orphaned portfolios with no user
        User, on_delete=models.CASCADE, related_name="portfolio", null=True)
    # User defined name for their portfolio
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Property(models.Model):
    Portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    streetAddress = models.CharField(max_length=300)
    city = models.CharField(max_length=300)
    Rent = models.CharField(max_length=10, null=True, blank=True)
    occupied = models.BooleanField()
    occupiedBy = models.CharField(max_length=10, null=True, blank=True)
    image = models.ImageField(
        upload_to='property/images', null=True, blank=True)

    def __str__(self):
        return self.streetAddress


class propDoc(models.Model):
    name = models.CharField(max_length=200)
    pdf = models.FileField(upload_to='property/files/')

    def __str__(self):
        return self.text


class Label(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class propDoc1(models.Model):
    Property = models.ForeignKey(Property, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    pdf = models.FileField(upload_to='property/files/')
    pdfPass = models.CharField(max_length=60)
    date_created = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        super().delete(*args, **kwargs)

    # def save(self, *args, **kwargs):

    #     # uploaded_file = request.FILES['pdf']
    #     # print(uploaded_file.name)
    #     # print(uploaded_file.content_type)
    #     # print("TESTING")
    #     # f = io.BytesIO(self.pdf.read())
    #     # pdfR = PyPDF2.PdfFileReader(f)
    #     # pdfW = PyPDF2.PdfFileWriter()
    #     # pdfW.cloneDocumentFromReader(pdfR)
    #     # for pageNum in range(pdfReader.numPages):
    #     #     pdfWriter.addPage(pdfReader.getPage(pageNum))
    #     # pdfW.encrypt("Test")
    #     # with open('SchoolSux.pdf', 'wb') as out:
    #     #     pdfW.write(out)
    #     # resultPdf = open(uploaded_file.name, 'wb')
    #     # pdfWriter.write(resultPdf)
    #     # resultPdf.close()

    #     # self.pdf.save()
    #     super().save(*args, **kwargs)

    # def encrypt(self):
    #     with open("Test2.pdf", "rb") as in_file:
    #         input_pdf = PdfFileReader(in_file)

    #     output_pdf = PdfFileWriter()
    #     output_pdf.appendPagesFromReader(input_pdf)
    #     output_pdf.encrypt("password")

    #     with open("Test2E", "wb") as out_file:
    #         output_pdf.write(out_file)

prodBuild/main/templates/main/base.html
{% load static %} 
<!doctype html>
<html>
  <head>
  
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style type="text/css">
        * {
          font-family: 'Montserrat', sans-serif;
        }
      

              a.btn {
          margin: 0 1em;
        }

        .clear {
            clear: both;
        }

        .nav-container {
            background: rgba(0,0,0,0.8);
          height: 100%;
        }

        .header {
          margin-top: -.9%;
        }

        nav ul li { 
          float: left;
          list-style: none;
          font-size: 130%;
          padding-left: 9%;
          padding-top: 1.5%;
        }

        nav ul li a { 
          color: white; 
          margin: 5px; 
          padding: 18px; 
          display: block; 
          margin-top: 0%;
          font-family: 'Montserrat', sans-serif;
        }

        nav ul li a:hover { 
        color: #000000; transition: color 0.7s ease-in; 
        }

        .header {
          background-color: #000033;
          width: 100%;
          top: 0;
          border: 1px;
          border-radius: 2px;
          box-shadow: 0 0 10px 0px rgba(12, 3, 25, 0.8);
        }

        .logo {
          float: left;
          padding: 10px 0;
          padding-left: 1%
        }

        @media screen and (max-width: 600px) {
        .header a:not(:first-child) {display: none;}
        .header a.logo {
            float: right;
            display: block;
          }
        }

        @media screen and (max-width: 478px) {
        .header
          
          1651
        }

        .content{
          padding-top: 10%
        }
    </style>

    <title>Secure Propery Management</title>
  </head>
  <body>
      <header>
      <div class="nav-container">
        <nav class="header">
          <div class="logo">
          <a href="index.html" class="pull-left"><img src="{% static '/images/Logo.png'%}" alt="LOGO" style="width:188px;height:100px;" ></a>
          </div>
          <ul>
          <li><a href="/view">Home</a></li>
          <li><a href="/create">Create a Portfolio</a></li>
          <li><a href="/login">Login</a></li>
          <li><a href="/register">Register</a></li>
          <li><a href="/logout">Logout</a></li>
          </ul>
          <div class="clear"></div>
        </nav>
      </div>
    </header>

    <div id="content" , name="content", class="main">
      <div class="row justify-content-center">
          <div class="col-8">
              <hr class="mt-0 mb-4">
            {% block content %}
            {% endblock %}
          </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

prodBuild/main/templates/main/create.html
{% extends 'main/base.html' %}

{% if user.is_authenticated %}

{% block title %} Create Portfolio {% endblock %}

{% block content %}
<form method="post" action="/create/">
    {% csrf_token %}
    <div class="input-group mb-3">
                <div class ="input-group-prepend">
                    <button type ="submit", name="save" class="btn btn-success">Create New</button>
                </div>
            {{form.name}}
        </div>
    </div>
</form>
{% endblock %}
{% else %}
<a href="/login">Login Here</a>
{% endif %}

prodBuild/main/templates/main/file_upload.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Upload File</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Upload File</button>
    </form>
{% endblock %}

prodBuild/main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}
Home Page
{%endblock%}
    {% block content %}
    <h1>Home Page</h1>
    {% endblock %} 

prodBuild/main/templates/main/portfolio.html
{%extends "main/base.html"%}
{% load static %} 

{% load crispy_forms_tags %}

{%block title%}
Portfolio
{%endblock%}

{%block content%}
    <style type="text/css">


    .card{
    border: none;
    transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
    overflow:hidden;
    border: 1px solid #000033;
    border-radius:5px;
    margin-bottom: 1.5rem;
    font-family: 'Montserrat', sans-serif;
    box-shadow: 0 0 5px 0 rgba(0,0,0,0.2);
    </style>
<div class="container mx-auto mt-4">
  <div class="row">
  {% for property in ls.property_set.all %}
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
    <img src="{% static '/images/Property2.png'%}" class="card-img-top" alt="Picture of {{property.streetAddress}}">
    <div class="card-body">
    <h5 class="card-title">{{property.streetAddress}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{property.city}}</h6>
    <p class="card-text">Occupied By {{property.occupiedBy}}</p>
    <p class="card-text">Rent €{{property.Rent}} p/m</p>
    <a href="/propertyview/{{property.id}}"class="btn btn-dark">View Files</a>
  </div>
  </div>
    </div>
    {% endfor %}
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
    <img src="{% static '/images/Property2.png'%}" class="card-img-top" alt="Picture of {{property.streetAddress}}">
    <div class="card-body">
    <h5 class="card-title">Add a Property</h5>
    <p class="card-text">
    <form method="post" action="#">
    {% csrf_token %}
    <div class="input-group mb-3">
        <ul>
        <p  class="card-text">Address: <input type="text", name="address"></p>
        <p  class="card-text">City: <input type="text", name="city"></p>
        <p  class="card-text">Tenant: <input type="text", name="occupiedBy"></p>
        <p  class="card-text">Rent: <input type="text", name="rent"></p>
        </ul>
    </div>
    <button type="submit", name="newProperty", value="newProperty" class="btn btn-success">Add Property</button>
    </form>
    </p>
  </div>
  </div>
    </div>    
</div>
  </div>
    {%endblock%}

prodBuild/main/templates/main/property.html
{% extends 'main/base.html' %}
{% load static %} 

{%block title%}
Property
{%endblock%}


{%block content%}
    <table class="table">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Property</th>
              <th scope="col">File</th>
              <th scope="col"><a href="/files/upload/">Upload</a></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
          {% for ls in ls %}
            <tr>
              <th scope="row">{{ ls.id }}</th>
              <td>{{ ls.Property }}</td>
              <td>{{ ls.name }}</td>
              <td><a href="{{ ls.pdf.url }}" target="_blank">Download</a></td>
              <form method="post" action="{% url 'file_delete' ls.pk %}">
              {%csrf_token%}
                <td><button type="submit" class="btn btn-danger btn-sm">Delete</button></td>
            </tr>
             {% endfor %}
          </tbody>
        </table>
        


{%endblock%}

prodBuild/main/templates/main/view.html
{%extends "main/base.html"%}
{% load static %} 
{% block title %}
View
{% endblock %}

{% block content %}
    <style type="text/css">


    .card{
    border: none;
    transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
    overflow:hidden;
    border: 1px solid #000033;
    border-radius:5px;
    margin-bottom: 1.5rem;
    font-family: 'Montserrat', sans-serif;
    box-shadow: 0 0 5px 0 rgba(0,0,0,0.2);
    </style>
<div class="container mx-auto mt-4">
  <div class="row">
  {% for pf in user.portfolio.all %}
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
    <img src="{% static '/images/Property2.png'%}" class="card-img-top" alt="Picture of {{pf.name}}">
    <div class="card-body">
    <h5 class="card-title">{{pf.name}} Portfolio</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{property.city}}</h6>
    <a href="/{{pf.id}}"class="btn btn-dark">View Properties</a>
  </div>
  </div>
</div>
    {% endfor %}

{% endblock %}